models:
  sentence_similarity: intfloat/multilingual-e5-large #PM-AI/bi-encoder_msmarco_bert-base_german
  llm: meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo #VAGOsolutions/Llama-3.1-SauerkrautLM-8b-Instruct
  stance_classifier: kapllan/deepset_gbert-large_stance_classifier
paths:
  logs: ../logs
  language_detection: ../models/lid.176.bin
  datasets: ../data/datasets
  data: ../data
  models: ../models
  user_data: ../data/user_data
metrics:
  tr_classification_model: matthews_correlation #f1 ; matthews_correlation
prompts:
  stance_detection: categorize_argument_zero_shot_cot
  make_sentence_concrete: make_sentence_concrete_1
  find_reasoning: find_reasoning
  extract_person: extract_person
thresholds:
    sentence_similarity: 0.8
database:
  chromadb: smart_opinion_default_collection
app:
  column_renaming:
    topic_original: Worum geht es?
    label: Haltung
    context: Kontext
    argument_reason: Modellbegründung für gewählte Haltung
    argument_original: Meinung
    # reasoning: Begründung für die Meinung
    reasoning_segment: Begründung für die Meinung
    person: Person
    party: Partei
    canton: Kanton
    similarity: Sem. Ähnlichkeit
    model_name: LLM
  neutral_limit: 5




